name: Discord Pull Request Notification

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          body: |
            {
              "content": "New Pull Request: ${{ github.event.pull_request.title }}\nBy: ${{ github.event.pull_request.user.login }}\n\n${{ github.event.pull_request.html_url }}",
              "avatar_url": "https://avatars.githubusercontent.com/u/193271640"
            }
